### ISSUE TITLE
Unicode characters in templates cause an error 

### ISSUE THREAD

**Issue by valq7711** [web2py/web3py#15]
Try insert  ՐՏ in  todo/templates/index.html 

![w3punic](https://user-images.githubusercontent.com/11394363/57571686-d2bb3780-7419-11e9-92e8-7aaad3480f33.png)

**Comment by mdipierro** [comment]
This would be a yatl issue. Anyway the error says that is invalid Unicode.
Maybe you inserted a Latin1 instead? If I post the template I can check

**Comment by valq7711** [comment]
it seems that it's all ok with yatl, I just add `encoding='utf8'` to open-call  of `read` method of `Template` class of web3py.core and now it works fine.
